### ISSUE TITLE
Clarification on integral_wrt_time_of_surface_direct_downwelling_shortwave_flux_in_air_1hour_Accumulation.nc	

### ISSUE THREAD

**Issue by chiaral** [planet-os/notebooks#22]
Hello! 
I need some clarifications on the variable: 

integral_wrt_time_of_surface_direct_downwelling_shortwave_flux_in_air_1hour_Accumulation.nc

The name suggests that is "direct" only.
However when I look at the metadata I have as name variable `ssrd`
![image (5)](https://user-images.githubusercontent.com/8453445/215597296-63fd98ca-f88c-4670-b055-4887b2562e92.png)

`ssrd` corresponds to this [variable](https://apps.ecmwf.int/codes/grib/param-db/?id=169) which explicitly states: This parameter comprises both direct and diffuse solar radiation.

Moreover, the units of this variable, based on the metadata, are J/m2 ; I don't think I have found within ERA5 documentation a variable that is representative of direct radiation that comes in J/m2, all those that mention direct are in W/m2. 

Can anyone clarify this? perhaps it was a simple naming error, and indeed this quantity is `ssrd` which includes both direct and diffuse radiation. 

Thanks!

**Comment by aluhamaa** [comment]
Hi @chiaral
 
I cannot check the direct vs direct + diffuse at the moment, however, the J/m2 should just reflect the fact that it is integral/accumulated variable and not flux. 

Regards
Andres

**Comment by chiaral** [comment]
Hi Andres!

Thanks so much for your quick reply, and of course for putting these data in AWS!

Yes, indeed, J/m2 vs W/m2 could be just a matter of units. So I guess if you could check which was the original variable corresponding to this specific quantities on the cloud would be great. 

I am happy to open a PR to fix the documentation after. 
Have a great day!

**Comment by etoodu** [comment]
Hi @chiaral,

I am so sorry for the wait. 
I checked and this variable seems to correspond to `Surface solar radiation downwards` variable, which in short is ssrd and units are J m-2.

**Comment by chiaral** [comment]
Thanks so much! 
I really appreciate your help on this. 
I had done a quick comparison between these data and the ssrd, in fact, and things seemed to line up pretty well. 
Thanks for double checking and confirming the source! 
Best,
