### ISSUE TITLE
inconsistent information for 1hour variables

### ISSUE THREAD

**Issue by xzenggit** [planet-os/notebooks#4]
Hello,

I recently found that some variables with `time1` dimension such as `precipitation_amount_1hour_Accumulation` ususally have corresponding `time1_bounds`  values. However, the `time1_bounds` values indicate that it's 3-hourly accumulated for precipitaiton rather than hourly, which is not consistent with the variable name `precipitation_amount_1hour_Accumulation`. Similar problems also exist in other non-instantaneous variables.  Following is an example.  Is `precipitation_amount_1hour_Accumulation` really 1-hourly accumualted precipitation or 3-hourly? How about other similar variables such as maimum/minimum temperature? Thank you.

```python
ds.time1
```
```
<xarray.DataArray 'time1' (time1: 40200)>
array(['2014-06-01T07:00:00.000000000', '2014-06-01T08:00:00.000000000',
       '2014-06-01T09:00:00.000000000', ..., '2019-01-01T04:00:00.000000000',
       '2019-01-01T05:00:00.000000000', '2019-01-01T06:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time1    (time1) datetime64[ns] 2014-06-01T07:00:00 ... 2019-01-01T06:00:00
Attributes:
    standard_name:  time
    bounds:         time1_bounds
```
```python
ds.time1_bounds.isel(time1=1).load()
```
```
<xarray.DataArray 'time1_bounds' (nv: 2)>
array(['2014-06-01T05:00:00.000000000', '2014-06-01T08:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
    time1    datetime64[ns] 2014-06-01T08:00:00
Dimensions without coordinates: nv

```
```python
ds.time1_bounds.isel(time1=0).load()
```
```
<xarray.DataArray 'time1_bounds' (nv: 2)>
array(['2014-06-01T04:00:00.000000000', '2014-06-01T07:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
    time1    datetime64[ns] 2014-06-01T07:00:00
Dimensions without coordinates: nv
```

**Comment by ecoflo** [comment]
@xzenggit - have you received a response to your question? After using the precipitation dataset, it seems the values are more consistent with 3-hourly than 1-hourly.

**Comment by aluhamaa** [comment]
@ecoflo Can you be a little more specific about how you came to that conclusion?
What variables did you use (and from what dataset), and against what did you compare them? I'm definitely going to investigate if something is not as it is supposed to be.

**Comment by ecoflo** [comment]
@aluhamaa we used the ERA5 data for Tanzania, loaded from the ERA5 bucket, stacked, cropped to Tanzania's extent. Then, we applied the following function (R).

`        if(grepl("precipitation_amount_1hour_Accumulation", vc.clprm[clp])){
          
          nrs <- stackApply(sras, ## sras is the cropped stack
                            indices = df.dates$date, ## df.dates transforms seconds in dates
                            fun = function(X, na.rm) sum(X)*3600,  ## to obtain results in hour
                            filename = out.nc,
                            overwrite=TRUE,
                            na.rm = TRUE)`

When summing the "hourly" data, we obtain values, which are about three times higher than precipitation values usually reported for Tanzania. For example, for Dar-es-Salaam we obtain a mean precipitation depth (at the district level) over the 1979-2021 period of ~3800mm per year. As a comparison, WB portal ([https://climateknowledgeportal.worldbank.org/country/tanzania-united-republic/climate-data-historical](here) indicates ~1200mm.

Happy to provide more details if required.

**Comment by etoodu** [comment]
@ecoflo We have used the same data in View2020 dashboard that you can find here: https://planetos.com/view2020/climatology
Based on that, in average, precipitation in Tanzania has been ~1031 mm (period 1991-2020). 
Can you specify the area you used to compute this data where you get 3800 mm year? 
Also, did you convert data to mm as ERA5 precipitation data is in meters by default. Is it possible that there is some issue in your function?

**Comment by ecoflo** [comment]
@etoodu & @aluhamaa - the problem was in the multiplication by 3600. We are used to work with RCM data, which are expressed in kg.m-2.s-1 (hence the multiplication by 3600 and 24 to obtain daily precipitation). Thank you for your prompt responses!
